
image: nikolajdl/gcloud-sdk-nodejs
build:
  stage: build
  script:
    - npm ci
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID app deploy app.yaml
  tags:
    - corfix
after_script:
  - rm /tmp/$CI_PIPELINE_ID.json